package application;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.RadioMenuItem;
import javafx.scene.control.ToggleGroup;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.CornerRadii;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class Quiz extends Application {
	BorderPane primaryLayout = new BorderPane();
	Scene scene = new Scene(primaryLayout);
	
	public static void main(String[] args) {
		launch();
	}
	
	// creates a "Color" menu in for changing the background color of the root Node
	private void setMenuBar() {
		ToggleGroup backgroundColors = new ToggleGroup();	
		Menu colorMenu = new Menu("Color");
		colorMenu.getItems().addAll(constructBackGroundColor("Yellow", Color.YELLOW, backgroundColors),
									constructBackGroundColor("Red", Color.RED, backgroundColors),
									constructBackGroundColor("Blue", Color.BLUE, backgroundColors), 
									constructBackGroundColor("Green", Color.GREEN, backgroundColors));
		MenuBar menuBar = new MenuBar(colorMenu);
		primaryLayout.setTop(menuBar);
	}
	
	// constructs each menu item in the "Color" menu
		RadioMenuItem constructBackGroundColor(String label, Color color, ToggleGroup backgroundColors) 
		{
			RadioMenuItem backgroundColor = new RadioMenuItem(label); 
			backgroundColor.setToggleGroup(backgroundColors);
			backgroundColor.setOnAction(e-> {
				primaryLayout.setBackground(new Background(new BackgroundFill(color, new CornerRadii(0), Insets.EMPTY)));
				});
			return backgroundColor;
		}

	@Override
	public void start(Stage primaryStage) throws Exception {
		// create questions
		Question question1 = new MultipleChoiceQuestion("What's the world's most populous country?", "China",
				"India",
				"United States",
				"China",
				"Indonesia");
		Question question2 = new MultipleChoiceQuestion("What's the course # of this course?", "CS 1102",
				"CS 1102",
				"CS 1134",
				"CS 1011",
				"CS 1101");
		Question question3 = new TrueFalseQuestion("Is the capital of the US California?", "FALSE");
		Question question4 = new TrueFalseQuestion("Is Trump the richest person in the world?", "FALSE");
		Question[] questions = new Question[] {question1, question2, question3, question4};
		
		// display the first question + the current score
		questions[0].showQuestion(primaryLayout);
		primaryLayout.setBottom(question3.getScoreLabel());
		
		// handle action events that will be generated by selecting a choice
		for(Question question: questions) {
			question.handleActionEvents(primaryLayout, questions, 4);
		}
		
		// set the initial color of the root Node's background
		primaryLayout.setBackground(new Background(new BackgroundFill(Color.hsb(200, 1.0, 0.5), new CornerRadii(0), Insets.EMPTY)));
		
		// set the menu bar and its components
		setMenuBar();
		
		// adjust the primary stage
		primaryStage.setTitle("Quiz Program");
		primaryStage.setScene(scene);
		primaryStage.setWidth(500); primaryStage.setHeight(300); primaryStage.setResizable(false);
		primaryStage.show();
	}

}
